version: '3.8'

services:
    postgres:
      image: postgres:13
      restart: always
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - 2001:5432
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - 5050:80
      depends_on :
        - postgres

    mysql:
      platform: linux/amd64
      image: mysql
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_PORT=3307
      ports:
        - 3307:3306
      volumes:
        - ./mysql_data:/var/lib/mysql

    phpmyadmin:
      platform: linux/amd64
      image: phpmyadmin/phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - PMA_HOST=mysql
      ports:
        - 8080:80


